apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-environment-provider-worker
  labels:
    app.kubernetes.io/name: etos-environment-provider-worker
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: environment-provider-worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-environment-provider-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-environment-provider-worker
    spec:
      serviceAccountName: etos-environment-provider-worker
      containers:
        - name: etos-environment-provider-worker
          image: registry.nordix.org/eiffel/etos-environment-provider-worker:191ed4e7
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: etos-environment-provider-worker
      terminationGracePeriodSeconds: 4250
